server:
  port: 8399

spring:
  liquibase:
    change-log: "classpath:db-migrations/changelog.xml"
    user: postgres
    password: webwelle32
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=dtp"
    username: postgres
    password: webwelle32

external:
  driver-service:
    host: localhost
    port: 5432